language: go
go:
  - 1.12.x

stages:
  - compile
  - package
  - deploy

env:
  global:
    # GITHUB_API_KEY
    - secure: "cYl8Htr8a5icMGVWd3M43nAy5ltUL/04gG6oGt9bsWi2OA56u11mx/LpQA68vkkRtx9QMP5xoTV418sVVATTIfsBiNuUR4KbCXoUfnIl5Q+1S8joPbgQxTcfazvrgJq9FURtW0wj0Sa0RwNT+PYtV6Bze+NJObd1tE9O+Befwmn53li2zNEV+lZXwbMgQk6g6tZvEsG5QrohfMXUg12i4kWchfkuNK/siNykcxUoQPGrJSp897n+YVPPbMZP04RfnbcSZPJ7Ru7QiG3f8iVW9cIdMpBg26NI/O/tVgbMn2wPbY1/C00GIAyoS5di2IYeORsL9cuBlhfKqsW0o6yYxb9hd60wmv6Zgnz1B2lTWcDR1rUiMO1jKJf8DMmdi6EKu5XNelyV0zOWb1YXSTu5p1ZF/w6AsaI5ByQdZWU0Hgv0ydiZ3+NrfR5FsaKKR/1S2fDSMHbeDHcOnRDTDuv0s1drdtnMVYAVii3BCsvLnaiPeWyQFbfn+xJ7vhD1788XEo/fwHxjjRpzlmReifriZvvuFGdMxDz6cY22RoDZ80Fjqrs4B5tSwCcu6bwYLvVC6unOLNgRCFDbPKLvWyJIv/S7VRXG7HaTRu+z3oz9sv8qFy2ZqVn0zb/Xxx4nE0SxGcCsNn3HH3xs1UY18UVdWqzJ2dpgw0sMJCIL6eH8NZk="
    - DOCKER_USERNAME=intelligide
    # DOCKER_PASSWORD
    - secure: "aGUC8q9aHiATX9r14xfwlA3nw1ROUXPWeNou1yz4uhC7vXR9UkY7DifQNNuMwEq7ephvtMFAao0zgLWFtVxYWB4QVwEKchCZMiORG4rRkN4Ej5uldDr5716HmANDmbXEEk51Qm+QSzV6uOIwIEWeFIkWy+VvM0n86D+NQksYSdgV3A8l0PVsDfcx4C2b+puLdEZOUByt7b1ATEe/b44CqHPmogFANOui+bX5xrVTC2tIHRrO5L82p7beGyaKtWoIuAacjyd29d1EBFmklOmeE5FI5rJP0oXfbOIovE4wGVIU9OCcNe6cH5CRYvaFMP1Tpj4J064ErFs5V05CN4OXRTUuU644CHAw5BauuI5k0CTjp1PErVSI+KJiKSI2fLOTq7FF/XDEuGlAks/rcQ/zsjCp7TZaTvh2Mv61IJgx/3SCw5QO9hzSk43b5U4VPwp7wIg6PmQoeLrAdwCUdCeM28Pf1JJiRyRw3eEcCY3zhiA6rGacJmL+hgRM5oUEt6Gk0f+WIiDMrnR5hlTz2nqQrZPwbT4rncYhukOa1eFK1baN4zvKRTKiye5jgBt6k+jFYLJ+duF15LFdHV0Uvp64TjSAvFiOMWLaQlAdoSvJaEcZdfrbTgeJJ4NwsrXZ5sUohsHPvhtiHXwsXLQakZaZ9A0+bGKisjRq0FisPdgpQk0="

####################
# OS Configuration #
####################

linux: &linux
  os: linux
  dist: xenial

osx: &osx
  os: osx

windows: &windows
  os: windows

#######################
# Tasks Configuration #
#######################

compile-task: &compile-task
  script:
    - go mod download
    - go run build.go build all

github-deploy-task: &github-deploy-task
  script: skip
  if: env(TRAVIS_TAG) IS present AND env(TRAVIS_TAG) IS NOT blank
  deploy:
    provider: releases
    api_key: ${GITHUB_API_KEY}
    skip_cleanup: true
    file:
      - build/bin/off-proxy
    on:
      repo: intelligide/off-api-proxy
      tags: true

########
# Jobs #
########

jobs:
  include:
    - stage: compile
      name: "Compile on Linux"
      <<: *linux
      <<: *compile-task

    - name: "Compile on macOS"
      <<: *osx
      <<: *compile-task

    - name: "Compile on Windows"
      <<: *windows
      <<: *compile-task

    - stage: package
      name: "Build Docker image"
      services:
        - docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t registry.gitlab.com/$DOCKER_USERNAME/off-proxy:dev .
        - docker push registry.gitlab.com/$DOCKER_USERNAME/off-proxy:dev

    - stage: deploy
      <<: *linux
      <<: *github-deploy-task

    - <<: *osx
      <<: *github-deploy-task

    - <<: *windows
      <<: *github-deploy-task

install:
  - mkdir -p $HOME/src
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/off-api-proxy
  - cd $HOME/src/off-api-proxy

