language: go
go:
  - 1.12.x

stages:
  - compile
  - package
  - deploy

env:
  global:
    # GITHUB_API_KEY
    - secure: "cYl8Htr8a5icMGVWd3M43nAy5ltUL/04gG6oGt9bsWi2OA56u11mx/LpQA68vkkRtx9QMP5xoTV418sVVATTIfsBiNuUR4KbCXoUfnIl5Q+1S8joPbgQxTcfazvrgJq9FURtW0wj0Sa0RwNT+PYtV6Bze+NJObd1tE9O+Befwmn53li2zNEV+lZXwbMgQk6g6tZvEsG5QrohfMXUg12i4kWchfkuNK/siNykcxUoQPGrJSp897n+YVPPbMZP04RfnbcSZPJ7Ru7QiG3f8iVW9cIdMpBg26NI/O/tVgbMn2wPbY1/C00GIAyoS5di2IYeORsL9cuBlhfKqsW0o6yYxb9hd60wmv6Zgnz1B2lTWcDR1rUiMO1jKJf8DMmdi6EKu5XNelyV0zOWb1YXSTu5p1ZF/w6AsaI5ByQdZWU0Hgv0ydiZ3+NrfR5FsaKKR/1S2fDSMHbeDHcOnRDTDuv0s1drdtnMVYAVii3BCsvLnaiPeWyQFbfn+xJ7vhD1788XEo/fwHxjjRpzlmReifriZvvuFGdMxDz6cY22RoDZ80Fjqrs4B5tSwCcu6bwYLvVC6unOLNgRCFDbPKLvWyJIv/S7VRXG7HaTRu+z3oz9sv8qFy2ZqVn0zb/Xxx4nE0SxGcCsNn3HH3xs1UY18UVdWqzJ2dpgw0sMJCIL6eH8NZk="
    - DOCKER_USERNAME=intelligide
    # DOCKER_PASSWORD
    - secure: "q6d3ypjipRAr2e8q/0CXUVx/BoRHAT0ilpvg4IWaFFdlpnofkGPhJTCgvGxb4F2x1aG2VN7oalnwI67cbMnH9Pt5G6aDC0BUsYV+Yp2MSltUTGwnf9CCbzxfxY4ju2DYR7CT+SzkHb7wlj6HNJx3vhK5FbVbeRfNxyb2Ic4yBTZf9+XvYt+46X2pwimLMaPGcsBXu5X5JBq8Z7qr/tNQuyCbW9pr9mTtlXSemcCQwClflghFhjdnhuphhnGKKsC2eTNoHYzpZDTfNriod1M/CpX/NLOz6otYnOp+ELlbMUESgyGFJktRDip5iXhtDqNGGtA0zQlNRux37bgUpvksGhvi4IUtj4wE8gZ0jOfXPDHl0MdAcDh+smRApkywS7EgkaNMDjJl430Zi1nsEHhq6Z4XeBdMs8hqg6cczHGjb9Ke4EksIas3qH7oz6gruLMyGrvup43oHHMRzgHTlY7/3+rLgBPx25cq67f8bKwq8sR1TZ8ZPg9fcUIx0KA7qpp96e0yNggv0Awm3199CRAw8xBKJT2xgUr3MBUGcSLrf6vjZi6EVc1FknaRORvP53/bpuLAiDZ22+GgzikvGdewYHF7OJFygpvQn2moYUU1BAMWm0Zt2D2wvvgB/ANdtK8haVFDlmv8d/z71JYZPMp0MpZa5mjP1OcfLf2R+9uQBLY="

####################
# OS Configuration #
####################

linux: &linux
  os: linux
  dist: xenial

osx: &osx
  os: osx

windows: &windows
  os: windows

#######################
# Tasks Configuration #
#######################

compile-task: &compile-task
  script:
    - go mod download
    - go run build.go build all

github-deploy-task: &github-deploy-task
  script: skip
  if: env(TRAVIS_TAG) IS present AND env(TRAVIS_TAG) IS NOT blank
  deploy:
    provider: releases
    api_key: ${GITHUB_API_KEY}
    skip_cleanup: true
    file:
      - build/bin/off-proxy
    on:
      repo: intelligide/off-api-proxy
      tags: true

########
# Jobs #
########

jobs:
  include:
    - stage: compile
      name: "Compile on Linux"
      <<: *linux
      <<: *compile-task

    - name: "Compile on macOS"
      <<: *osx
      <<: *compile-task

#    - name: "Compile on Windows"
#      <<: *windows
#      <<: *compile-task

    - stage: package
      name: "Build Docker image"
      <<: *linux
      services:
        - docker
      script:
        - echo "$DOCKER_PASSWORD" | docker login registry.gitlab.com -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t registry.gitlab.com/$DOCKER_USERNAME/off-api-proxy:dev .
        - docker push registry.gitlab.com/$DOCKER_USERNAME/off-api-proxy:dev

    - stage: deploy
      <<: *linux
      <<: *github-deploy-task

    - <<: *osx
      <<: *github-deploy-task

#    - <<: *windows
#      <<: *github-deploy-task

install:
  - mkdir -p $HOME/src
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/off-api-proxy
  - cd $HOME/src/off-api-proxy

