language: go

services:
  - docker

go:
  - 1.12.x

os:
  - linux
  - osx
  - windows

stages:
  - compile
  - test
  - package
  - deploy


jobs:
  include:
    - stage: compile
      script:
        - go mod download
        - go run build.go build all

    - stage: package
      name: "Build Docker image"
      script:
#        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t off-proxy ./package/docker
        - docker images
#        - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
#        - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo

install:
  - mkdir -p $HOME/src
  - mv $TRAVIS_BUILD_DIR $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/off-api-proxy
  - cd $HOME/src/off-api-proxy

