provider = "https://world.openfoodfacts.org/"

[cache]
    enabled = true
    adapter = "memory"

    [cache.memory]
        max_memory = 100
        interval = 60

    [cache.redis]
        max_memory = 100
        key = "collectionName"
        conn = 6039
        dbNum = 0
        password = "secret"

[logs]

    # RFC5424 log message levels.
    # 0 => Emergency: system is unusable
    # 1 => Alert: action must be taken immediately
    # 2 => Critical: critical conditions
    # 3 => Error: error conditions
    # 4 => Warning: warning conditions
    # 5 => Notice: normal but significant condition
    # 6 => Informational: informational messages
    # 7 => Debug: debug-level messages
    level = 5
